language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - nosetests --with-coverage --cover-package=textlines
    - flake8 setup.py textlines tests
after_success:
  - coveralls
  - cd docs && PYTHONPATH=.. make singlehtml